# Generated by Django 4.2.11 on 2024-04-28 10:21

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'このユーザー名は既に使用されています。'}, help_text='※150文字以下の文字や数字、一部の記号で入力したください。', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザ名')),
                ('channel_name', models.CharField(blank=True, max_length=150, verbose_name='チャンネル名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Eメールアドレス')),
                ('is_staff', models.BooleanField(default=False, help_text='ユーザーがこの管理サイトにログインできるかどうかを指定します。', verbose_name='ユーザステータス')),
                ('is_member', models.BooleanField(default=False, help_text='このユーザが契約しているかを区別します。', verbose_name='会員ステータス')),
                ('is_active', models.BooleanField(default=True, help_text='このユーザーをアクティブとして扱うかどうかを指定します。アカウントを削除する代わりに、これを選択解除してください。', verbose_name='アクティブユーザ')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
