# Generated by Django 4.2.11 on 2024-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='cID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
