# Generated by Django 4.2.11 on 2024-04-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_merchandise_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=255)),
                ('cEmail', models.EmailField(blank=True, max_length=100)),
                ('cPassword', models.CharField(max_length=254)),
                ('cPhone', models.CharField(blank=True, default='', max_length=20)),
                ('cAddr', models.CharField(blank=True, default='', max_length=255)),
                ('cCountry', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cBirthday', models.DateField(null=True)),
                ('cSex', models.CharField(default='N', max_length=2)),
            ],
        ),
    ]
