# Generated by Django 4.2.11 on 2024-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cImage',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='member',
            name='cImageName',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
