# Generated by Django 4.2.11 on 2024-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_member_cimage_member_cimagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cFavor',
            field=models.TextField(null=True),
        ),
    ]
