# Generated by Django 4.2.11 on 2024-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_member_cfavor_remove_member_cpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cNickName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
