# Generated by Django 4.2.11 on 2024-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_member_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='cInventory',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='memberMerchandise',
        ),
    ]
