# Generated by Django 4.2.11 on 2024-05-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_membermerchandise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memberMerchandise',
        ),
    ]
