# Generated by Django 4.2.11 on 2024-05-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_membermerchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberMerchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cRank', models.IntegerField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.merchandise')),
            ],
            options={
                'unique_together': {('member', 'merchandise')},
            },
        ),
    ]
