# Generated by Django 4.2.11 on 2024-05-05 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_membermerchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermerchandise',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
