# Generated by Django 4.2.11 on 2024-05-08 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_membercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cCreatedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
