# Generated by Django 4.2.11 on 2024-05-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_member_ccreatedtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memberMerchandise',
        ),
    ]
