# Generated by Django 4.2.11 on 2024-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_memberorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberorder',
            old_name='cOrderInfo',
            new_name='orderInfo',
        ),
    ]
